import { Image } from '@nextui-org/react'
import React from 'react'

function page() {



    const vendingProducts = {
        "Chocolate Candy": [
            "3 Musketeers®",
            "Cadbury® Caramello",
            "Hershey’s® Almond",
            "Hershey’s Almond Joy",
            "Hershey’s Cookies ‘n Creme",
            "Hershey’s Fifth Avenue®",
            "Hershey’s Kit-Kat Extra Crispy",
            "Hershey’s Milk Chocolate",
            "Hershey’s Mr. Goodbar®",
            "Hershey’s Zero®",
            "Lance® Peanut Bar",
            "M&M’s® Peanut",
            "M&M’s Peanut (King)",
            "M&M’s Plain",
            "M&M’s Plain (King)",
            "Milky Way®",
            "Nestle® Baby Ruth®",
            "Nestle Butterfinger®",
            "Hershey’s Payday",
            "Hershey’s Reese’s® Peanut Butter Cups",
            "Hershey’s Reese’s Pieces",
            "Hershey’s Reese’s Pieces Big Bag",
            "Hershey’s Reese’s Whips",
            "Hershey’s Rolo®",
            "Hershey’s Whatchamacallit®",
            "Hershey’s Whoppers®",
            "Nestle Butterfinger Crisp",
            "Nestle Crunch",
            "M&M/Mars® Snickers®",
            "M&M/Mars Snickers Almond",
            "M&M/Mars Snickers Dark",
            "M&M/Mars Snickers King",
            "Tootsie Roll®",
            "Twix® Caramel"
        ],
        "Hard Candy": [
            "Gobstopper® Chewy",
            "Hot Tamales® Fire",
            "Jolly Rancher® Sour",
            "Nerds® Grape & Strawberry",
            "Now & Later® Classic",
            "Now & Later Raspberry",
            "Now & Later Soft Bar",
            "Now & Later Tropical",
            "Now & Later Wild",
            "Runts® Chewy",
            "Shockers™",
            "Skittles®",
            "Skittles Crazy Cores",
            "Skittles Sour",
            "Skittles Tropical",
            "Skittles Wild Berry",
            "Sour Patch Kids® Extreme",
            "Sour Patch Kids Fruit",
            "Sour Patch Kids Peach",
            "Sour Patch Kids Watermelon",
            "Starburst®",
            "Starburst California",
            "Starburst FaveREDs",
            "Starburst Fruit & Creme",
            "Starburst GummiBursts™",
            "Starburst Sour Chews",
            "Starburst Tropical",
            "Sugar Babies®",
            "Twizzlers™ Rainbow",
            "Twizzlers Strawberry"
        ],
        "Gum": [
            "Big Red®",
            "Doublemint™",
            "Juicy Fruit®",
            "Spearmint™"
        ],
        "Roll Candy & Mints": [
            "Life Savers® Pep O Mint®",
            "Life Savers Spear O Mint®",
            "Life Savers Wint O Green®",
            "Life Savers Five Flavor",
            "Rolaids®"
        ],
        "Chip Products (Small Bags)": [
            "BBQ Chips",
            "Bugles® Hot & Spicy",
            "Bugles® Nacho",
            "Bugles® Regular",
            "Cheetos® Cheddar Jalapeno",
            "Cheetos® Crunchy",
            "Cheetos® Flaming Hot",
            "Corn Chips BBQ",
            "Corn Chips Regular",
            "Cracker Jack® Original",
            "Doritos® Cool Ranch",
            "Kosher Dill",
            "Munchos®",
            "Potato Chips Regular",
            "Quaker® Snack Mix Kid Mix",
            "Ripple Chips",
            "Ruffles® Cheddar & Sour Cream",
            "Ruffles® Cheddar Baked Potato",
            "Salt and Vinegar",
            "SunChips® French Onion",
            "SunChips® Garden Salsa",
            "SunChips® Harvest Cheddar",
            "SunChips® Regular"
        ],
        "Chip Products (Big Bags)": [
            "Andy Capp’s® Hot Chili Cheese",
            "Andy Capp’s® Hot Fries",
            "Bugles® Caramel",
            "Bugles® Chocolate",
            "Bugles® Nacho",
            "Bugles® Original",
            "Cheetos® Cheddar Baked Potato",
            "Cheetos® Crunchy",
            "Cheetos® Crunch Cheddar",
            "Cheetos® Flamin’ Hot",
            "Cheetos® Jalapeno Cheddar",
            "Combos® Cheddar",
            "Combos® Cheese Cracker",
            "Combos® Nacho",
            "Combos® Pepperoni",
            "Combos® Pizza",
            "Doritos® Blazin’ Buffalo & Ranch",
            "Doritos® Cool Ranch",
            "Doritos® Late Night",
            "Doritos® Nacho",
            "Funyuns® Flamin’ Hot Onion",
            "Lays® Cheddar & Sour Cream",
            "Lays® Hot & Spicy",
            "Lays® KC Master BBQ",
            "Lays® Regular",
            "Muchos®",
            "Pretzels Honey Wheat",
            "Ruffles® Cheddar & Sour Cream",
            "Smartfood® White Cheddar Popcorn",
            "SunChips® Original"
        ],
        "Baked Chips": [
            "BBQ",
            "Cheddar & Sour Cream",
            "Cheetos®",
            "Cheetos® Hot",
            "Nachos",
            "Quaker® Munchies Cheddar Mix",
            "Regular",
            "Sour Cream & Onion"
        ],
        "Pastry Products": [
            "Cheese Rounds",
            "Cherry Cheese Claw",
            "Chocolate Chip Fudge Brownie",
            "Cinnamon Coffee Cakes",
            "Cinnamon Roll",
            "Cloverhill Bakery® Big Bear Claw",
            "Cloverhill Bakery® Big Cheese Claw",
            "Cloverhill Bakery® Big Dutch Apple",
            "Cloverhill Bakery® Big Texas Big/Crunch",
            "Cloverhill Bakery® Blasters- Apple",
            "Cloverhill Bakery® Blasters- Blueberry",
            "Cloverhill Bakery® Blasters- Cherry",
            "Cloverhill Bakery® Blasters- Strawberry",
            "Cloverhill Bakery® Blueberry Cheese Claw",
            "Cloverhill Bakery® Cinnamon Roll Big Texas",
            "Cloverhill Bakery® Cream Cheese Coffee Cake",
            "Cloverhill Bakery® Danish- Apple Round",
            "Cloverhill Bakery® Danish- Big Pecan",
            "Cloverhill Bakery® Danish- Cheese Round",
            "Cloverhill Bakery® Danish- Cherry",
            "Cloverhill Bakery® Danish- Claw",
            "Cloverhill Bakery® Donuts- Chocolate",
            "Cloverhill Bakery® Donuts- Chocolate Chip Double",
            "Cloverhill Bakery® Donuts- Chocolate Double",
            "Cloverhill Bakery® Donuts- Chocolate Glazed",
            "Cloverhill Bakery® Donuts- Gem Crunch",
            "Cloverhill Bakery® Donuts- Gem Mixed",
            "Cloverhill Bakery® Donuts- Gem Sugar",
            "Cloverhill Bakery® Donuts- Glazed",
            "Cloverhill Bakery® Gold Pound Cake",
            "Cloverhill Bakery® Strawberry Cheese Claw",
            "Cloverhill Bakery® Supreme Big Horn",
            "Dolly Madison® Dunkin’ Sticks",
            "Dolly Madison® Fried Pies- Apple",
            "Dolly Madison® Zingers- Chocolate",
            "Dolly Madison® Zingers- Cream",
            "Dolly Madison® Zingers- Raspberry",
            "Dolly Madison® Zingers- Vanilla",
            "Kellogg’s® Pop-Tarts Apple Strudel",
            "Kellogg’s® Pop-Tarts Blueberry",
            "Kellogg’s® Pop-Tarts Brown Sugar Cinnamon",
            "Kellogg’s® Pop-Tarts Cherry",
            "Kellogg’s® Pop-Tarts Chocolate Chip",
            "Kellogg’s® Pop-Tarts Cinnamon",
            "Kellogg’s® Pop-Tarts Hot Fudge",
            "Kellogg’s® Pop-Tarts S’mores",
            "Kellogg’s® Rice Krispies",
            "Mrs. Freshley’s® 3 Pack Pecan Spins",
            "Mrs. Freshley’s® Apple Round",
            "Mrs. Freshley’s® Bake Shop Apple Ugly",
            "Mrs. Freshley’s® Bake Shop Blueberry Ugly",
            "Mrs. Freshley’s® Bake Shop Chocolate Chip Ugly",
            "Mrs. Freshley’s® Bake Shop Chocolate Creme Cake",
            "Mrs. Freshley’s® Bake Shop Lemon Creme Cake",
            "Mrs. Freshley’s® Bake Shop Orange Crush",
            "Mrs. Freshley’s® Bake Shop Pineapple Slice",
            "Mrs. Freshley’s® Bake Shop Strawberry Creme",
            "Mrs. Freshley’s® Bake Shop Vanilla Creme Cake",
            "Mrs. Freshley’s® Cake- Carrot",
            "Mrs. Freshley’s® Creamy Curl Cream Chocolate",
            "Mrs. Freshley’s® Cupcakes- Banana Pudding",
            "Mrs. Freshley’s® Cupcakes- Chocolate",
            "Mrs. Freshley’s® Cupcakes- Vanilla",
            "Mrs. Freshley’s® Donuts- Mini Cinnamon",
            "Mrs. Freshley’s®Donuts- Mini Powdered",
            "Mrs. Freshley’s® Honey Bun- Chocolate Iced",
            "Mrs. Freshley’s® Honey Bun- Glazed",
            "Mrs. Freshley’s® Honey Bun- Iced",
            "Mrs. Freshley’s® Honey Bun- White Iced",
            "Mrs. Freshley’s® Jelly Swirl",
            "Mrs. Freshley’s® Raspberry Fingers"
        ],
        "Ice Cream Selections": [
            "Toasted Almonds",
            "Strawberry Shortcake",
            "Chocolate Eclair",
            "Ice Cream Sandwich",
            "Snickers® King Size",
            "Fudge Bar",
            "Creamsicle",
            "Froz Fruit Strawberry",
            "Froz Fruit Coconut",
            "Chipwhich® Vanilla",
            "Klondike®",
            "Haggen Dazs® Vanilla Bars"
        ],
        "Frozen Food Selections": [
            "Bacon Cheeseburger",
            "BBQ Chicken Sandwich",
            "BBQ Pork Rib Sandwich",
            "White Castle® Cheeseburgers",
            "Hot Pockets® Pepperoni Pizza",
            "Hot Pockets® Ham & Cheese",
            "5′ Round Pizzas",
            "Angus Cheeseburger",
            "Chicken Cordon Bleu"
        ],
        "Healthy Snack Machine Items": [
            "Nature Valley® Granola Bars",
            "Nutri-Grain® Bars",
            "General Mills® Granola Bars",
            "Snackwells®",
            "Kellogg’s® Special K Bars",
            "Kars® Trail Mix",
            "Welch’s® Fruit Snacks",
            "Mr. Nature® Trail Mix",
            "Sun Chip®",
            "Smartfood® Popcorn",
            "Rold Gold® Honey Wheat Braids",
            "Baked Lays® Chips",
            "Lays® Kettle Cooked Chips",
            "Keystone® Veggie Chips Baked",
            "Popcorn Indiana® Popcorn",
            "Stacy’s® Pita Chips",
            "Samai® Plantain Chips"
        ],
        "Premium Selections": [
            "Kind Bars",
            "Power Bars",
            "Cliff Bars",
            "Pure Protein Bars"
        ]
    };



    return (
        <div className=" min-h-screen overflow-y-scroll hidescroll  items-center justify-between bg-black">
            <Image className='w-96 mt-0 h-96 object-cover' alt='hero' src='https://images.unsplash.com/photo-1578783204979-27a2e3de3746?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' />
            {Object.keys(vendingProducts).map(category => {
                return (
                    <div className="text-white px-3">
                        <h1 className='text-black bg-white text-2xl font-bold'>{category}</h1>
                        <div>
                            {vendingProducts[category].map(product => {
                                return (
                                    <p>{product}</p>
                                )
                            })}
                        </div>
                    </div>
                )
            })}
        </div>
    )
}

export default page